### ISSUE TITLE
Add visual identity

### ISSUE THREAD

**Issue by sergefdrv** [replica-io/replica-io#3]
Successful projects need attractive visual identity, i.e. a nice and meaningful logo. So the project is to get a nice and meaningful logo soon.

**Comment by sergefdrv** [comment]
Here's a sketch of the logo:
![replica_io-logo](https://user-images.githubusercontent.com/11386423/224306053-9138e1bd-2e1f-4f65-bf63-3c3b3a79e78b.png)

Firstly, the outline resembles DNA, which has inherent redundancy, as well as the ability to replicate and recover from damage. This thus symbolizes the core idea behind the project.

Secondly, the two horizontal strokes depict an equality sign between two branches below. This emphasizes that replication maintains identical copies. At the same time, the strokes represent communication between replicas, which can be disturbed (red stroke), but reconciles later (blue stroke).

Finally, the curved lines refer to the lambda letter, which draws a connection to lambda calculus and functional programming paradigm, the core property of which is composability - one of the core concept in the project.

**Comment by jsoares** [comment]
I'm curious about what a generative AI will put out if you feed it that description.

**Comment by sergefdrv** [comment]
Here's an attempt to make the logo in vector graphics:

![replica_io-logo](https://user-images.githubusercontent.com/11386423/224454502-a0584f3b-e0fb-475c-a6ba-50e25cf08247.png)

**Comment by sergefdrv** [comment]
And a B/W option:

![replica_io-logo-4-bw](https://user-images.githubusercontent.com/11386423/224481248-17e8b746-033a-4662-be4c-17eadadf2cf1.png)

**Comment by sergefdrv** [comment]
Another option:

![replica_io-logo-5-bw](https://user-images.githubusercontent.com/11386423/224481922-43697ac9-34a5-4c76-b050-ad19d4d7183d.png)

**Comment by sergefdrv** [comment]
And straight:

![replica_io-logo-straight-128x128](https://user-images.githubusercontent.com/11386423/224483982-b41b19a4-56d2-4a3a-a902-041554b8984e.png)

**Comment by sergefdrv** [comment]
The last version looks good enough.
