### ISSUE TITLE
Explore Kafka Raft implementation

### ISSUE THREAD

**Issue by sergefdrv** [replica-io/replica-io#32]
Explore [Kafka Raft](https://github.com/apache/kafka/tree/3.6.0/raft) implementation and summarize the findings.

**Comment by nikoladsp** [comment]
Following is an overview of [Kafka Raft implementation](https://github.com/apache/kafka/tree/3.5.1/raft), as of commit [2c6fb6c5](https://github.com/apache/kafka/commit/2c6fb6c54472e90ae17439e62540ef3cb0426fe3).

### Build instructions

In case you want to build from source, following are short instructions:

##### Prerequisites

- JDK 11
- Gradle 8
- Scala 2.13 (to run [TestRaftServer.scala](https://github.com/apache/kafka/blob/3.5.1/core/src/main/scala/kafka/tools/TestRaftServer.scala)) 

##### Build

1. `cd /tmp` (or whatever)
2.` git clone https://github.com/apache/kafka.git`
3. `cd kafka`
4. `git checkout 3.5.1`
5. `./gradlew jar -PscalaVersion=2.13`

##### Test run

`cd raft && bin/test-kraft-server-start.sh --config config/kraft.properties`

### General Structure

**Comment by sergefdrv** [comment]
@nikoladsp Thanks for doing this; I appreciate your efforts. Your overview somewhat summarizes the role of Kafka Raft in the system, but it doesn't give any insight into how it's implemented in code. In particular, we need to learn how the protocol logic is expressed in the code and how it approaches modularity, concurrency, and, to certain extend, debugging, validation, and analysis. I would like to have an in-depth overview of this project, similar to [others](https://github.com/replica-io/replica-io/wiki/State-of-the-art-exploration).

Below are some comments.

> Moreover, the same event-driven mechanism is also used to track all metadata across the cluster.

Do you mean _event-sourcing_ mechanism instead?

> Instead of the controller sending updates to the brokers, controllers fetch the metadata via a MetadataFetch API.

Do you mean that _brokers_ fetch the metadata? Would you mind adding a link to the code where the `MetadataFetch` API is defined?

**Comment by nikoladsp** [comment]
It is not yet finished, I will add concrete data - just did not want to lose stuff

**Comment by sergefdrv** [comment]
@nikoladsp Are you still working on this?

**Comment by nikoladsp** [comment]
I will during weekend

**Comment by nikoladsp** [comment]
For the reference this is (generated, so maybe not accurate):

![kraft class diagram](https://github.com/replica-io/replica-io/assets/7402902/a1450c3f-4ead-4b2d-af1c-c97feca98161) 

**KafkaRaftClient** object is created and initialized first. Part of this process is also belonging **QuorumState** object initialization which is read from storage (e.g. file). In turn, **ElectionState** is created. Important fields of **QueorumState** are:

- clusterId
- leaderId
- leaderEpoch
- votedId
- appliedOffset
- currentVoters
- data_version

**Comment by nikoladsp** [comment]
Please, let me know what I shall do to improve to the above. I am getting my life back after really hard period, so will be much more available.

**Comment by sergefdrv** [comment]
@nikoladsp Thank you for helping with this task. Unless you have already discovered and would like to summarize something else regarding how the protocol logic is expressed in the code and how it approaches modularity, concurrency, and, to certain extend, debugging, validation, and analysis, I think it would make more sense if you prepare for your future contributions by getting familiar with other things from [this list](https://github.com/replica-io/replica-io/issues/7), as well as learning Rust. I would then take over and conclude the exploration of Kafka Raft implementation. What do you think?

**Comment by nikoladsp** [comment]
Sounds good to me.

**Comment by nikoladsp** [comment]
Hi @sergefdrv, I am on vacation for the rest of the week and will try to go over https://github.com/nrc/r4cppp in order to familiarize myself with Rust.

**Comment by sergefdrv** [comment]
Following is an overview of [Apache Kafka's](https://github.com/apache/kafka) Raft implementation, as of version [3.6.0](https://github.com/apache/kafka/tree/3.6.0/raft) (September 2023).

### General Structure

[Apache Kafka](https://kafka.apache.org/) is a widely used open-source distributed event streaming platform. Starting version [3.3.1](https://kafka.apache.org/downloads#3.3.1), Kafka includes production support for a self-managed mode using KRaft, a protocol based on the [Raft Consensus Protocol](https://www.usenix.org/system/files/conference/atc14/atc14-paper-ongaro.pdf). The self-managed mode was first released for early access in version [2.8.0](https://kafka.apache.org/downloads#2.8.0). The KRaft protocol is implemented in Java and represented with the [`KafkaRaftClient`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L142) class, which is integrated with the rest of Kafka code base by means of the [`KafkaRaftManager`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L130) class implemented in Scala.

`KafkaRaftClient` implements the [`RaftClient`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftClient.java#L31) interface, which defines methods for getting information about the protocol state (e.g. the current high watermark, leader and epoch, log end offset, etc.), registering listeners implementing the [`RaftClient.Listener`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftClient.java#L33) interface (to be called on committed records, installed snapshots, changes to leadership, as well as shutdown events), creating snapshots, resigning from leadership, and submitting new records to be appended to the replicated log. The `RaftClient` interface is exposed through the [`client`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L125) method of the [`RaftManager`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L112) trait, implemented by `KafkaRaftManager`.

`KafkaRaftClient` is generic over the log record type and requires the following external dependencies, most of which are represented with abstract interfaces:
 - [`RecordSerde`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/common/serialization/RecordSerde.java#L28) to serialize and deserialize records,
 - [`NetworkChannel`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/NetworkChannel.java#L25) to communicate with peer nodes,
 - [`ReplicatedLog`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/ReplicatedLog.java#L27) to manipulate the local instance of the replicated log,
 - [`QuorumStateStore`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/QuorumStateStore.java#L23) to save and read KRaft quorum state information,
 - [`Time`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/utils/Time.java#L31) to access the local clock,
 - [`Metrics`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/metrics/Metrics.java#L69) to update telemetry metrics,
 - [`ExpirationService`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/ExpirationService.java#L21) to create futures expiring after a timeout,
 - [`LogContext`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/utils/LogContext.java#L33) to create diagnostic loggers with context,
 - [`RaftConfig`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftConfig.java#L50) to read the KRaft quorum configuration.

`KafkaRaftClient` is a completely passive component; it has to be driven by repeatedly calling the [`poll`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2291) method. This is done in the [`RaftIoThread`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L54) class, which extends abstract class [`ShutdownableThread`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/ShutdownableThread.java#L28). Once started, `ShutdownableThread` repeatedly calls the [`doWork`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/ShutdownableThread.java#L123) method until the thread gets shut down or the method throws an exception. `RaftIoThread` simply invokes `KafkaRaftClient.poll()` in its [`doWork`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L62) method and handles any thrown exceptions using the supplied instance of the [`FaultHandler`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/fault/FaultHandler.java#L24) interface. Polling is usually implemented by doing non-blocking checks for time-related and internal events using a current timestamp obtained from [`Time`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/utils/Time.java#L31), then blocking and waiting for an external event with a timeout until the next expected time-related event, e.g. as [here](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2291-L2314). This seems to be a common pattern in Kafka's code base.

`KafkaRaftClient` exposes public methods that can be called concurrently with the `poll` method. To ensure consistency, the affected pieces of internal state and sub-components are carefully protected using the synchronization primitives and typical idioms supported by Java, such as [synchronized methods](https://docs.oracle.com/javase/tutorial/essential/concurrency/syncmeth.html), [intrinsic locks](https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html), [atomic access](https://docs.oracle.com/javase/tutorial/essential/concurrency/atomic.html), [guarded blocks](https://docs.oracle.com/javase/tutorial/essential/concurrency/guardmeth.html), as well as [high-level concurrency objects](https://docs.oracle.com/javase/tutorial/essential/concurrency/highlevel.html) like [lock objects](https://docs.oracle.com/javase/tutorial/essential/concurrency/newlocks.html), [concurrent collections](https://docs.oracle.com/javase/tutorial/essential/concurrency/collections.html), and [atomic variables](https://docs.oracle.com/javase/tutorial/essential/concurrency/atomicvars.html).

The code uses the [`CompletableFuture`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) class for scheduling actions depending on a certain event in future. The supplied instance of the [`ExpirationService`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/ExpirationService.java#L21) interface (implemented by the [`TimingWheelExpirationService`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/TimingWheelExpirationService.scala#L37) class) is used to create instances of `CompletableFuture` that will fail with [`TimeoutException`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/errors/TimeoutException.java#L22) if not completed before the specified timeout expires. The [`FuturePurgatory`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/internals/FuturePurgatory.java#L43) interface implemented by the [`ThresholdPurgatory`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/internals/ThresholdPurgatory.java#L27) class is used to create futures that can be completed when a certain threshold value is reached. Futures created with `FuturePurgatory` expire after the specified timeout, so `ThresholdPurgatory` is implemented in terms of `ExpirationService`.

Attempting to optimize performance, Kafka tries to avoid copying significant amounts of data, e.g. achieving efficient zero-copy data transmission with the [`TransferableChannel`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/network/TransferableChannel.java#L29) interface. Memory pools, represented with the [`MemoryPool`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/memory/MemoryPool.java#L26) interface, are employed to reuse allocated memory blocks. Results of object serialization are cached using [`ObjectSerializationCache`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/protocol/ObjectSerializationCache.java#L32). 

### Communication

Communication between KRaft peers follows the remote procedure call (RPC) pattern. The communication layer is represented with the [`NetworkChannel`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/NetworkChannel.java#L25) interface. The interface assumes _best-effort_ service only, i.e. it does not guarantee ordering of requests or even that every outbound request will receive a response. 

Requests are represented with abstract class [`RaftRequest`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java#L23C23-L23C34). `RaftRequest` has two sub-classes: [`RaftRequest.Inbound`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java#L48) and [`RaftRequest.Outbound`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java#L65) representing inbound and outbound requests, respectively.  Similarly, responses are represented with abstract class [`RaftResponse`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftResponse.java#L21), which also has two sub-classes: [`RaftResponse.Inbound`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftResponse.java#L40) and [`RaftResponse.Outbound`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftResponse.java#L62) representing inbound and outbound responses, respectively. Requests and the corresponding responses are matched by an assigned integer identifier, correlation ID, which can be generated using the [`newCorrelationId`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/NetworkChannel.java#L30) method of `NetworkChannel`.

Outbound requests are initiated with the _non-blocking_ [`send`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/NetworkChannel.java#L37) method of `NetworkChannel`. `RaftRequest.Outbound` specifies the destination node ID and includes a future, [`completion`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java#L67), that is completed by `NetworkChannel` when it receives the response or the request times out. Inbound requests are passed to the [`handle`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2283) method of `KafkaRaftClient`. `RaftRequest.Inbound` also include a future, [`completion`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftRequest.java#L49), that should be completed by `KafkaRaftClient` with a response or exception. [`KafkaRaftManager`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L130) adapts this API in the [`handleRequest`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/RaftManager.scala#L213) method to using inbound requests represented by [`RequestHeader`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/requests/RequestHeader.java), [`ApiMessage`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/protocol/ApiMessage.java#L23), and timestamp, whereas outbound responses are represented by a future completed with `ApiMessage`. 

The [`KafkaNetworkChannel`](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala#L92) class implements the `NetworkChannel` interface. The implementation is based on abstract class [`InterBrokerSendThread`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L43), which is inherited from `ShutdownableThread`. It requires an instance of the [`KafkaClient`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/clients/KafkaClient.java#L29) interface providing a non-blocking network client and works by repeatedly calling the [`pollOnce`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L104) method, which [calls](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L89) abstract method [`generateRequests`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L74) for new requests, [puts](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L90) them into an _unbounded_ buffer represented by the [`UnsentRequests`](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L213) class, and then [sends](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L146) the buffered requests to the network client, as long as it is [ready](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L145). The request buffer is periodically [cleaned up](https://github.com/apache/kafka/blob/3.6.0/server-common/src/main/java/org/apache/kafka/server/util/InterBrokerSendThread.java#L181) from timed out requests. `RaftSendThread` simply keeps pending requests in an [_unbounded_ queue](https://github.com/apache/kafka/blob/3.6.0/core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala#L69) until they are picked by `InterBrokerSendThread`. [`NetworkClient`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java#L73) implements the `KafkaClient` interface based on the [`Selector`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/network/Selector.java#L87) class for doing non-blocking multi-connection network I/O, as well as on the [`ChannelBuilder`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/network/ChannelBuilder.java#L29) interface for creating instances of the [`KafkaChannel`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java#L67) class representing a communication channel to a remote node.
### Consensus Protocol Implementation

The KRaft protocol is implemented by the the [`KafkaRaftClient`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L142) class and its sub-components. `KafkaRaftClient` initializes and coordinates sub-components, handles inbound RPC requests and responses, triggers transitions between protocol states, and initiates outbound RPC requests. The main sub-components are the following:
 - [`RaftMessageQueue`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RaftMessageQueue.java#L26) implemented by [`BlockingMessageQueue`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/internals/BlockingMessageQueue.java#L29) for maintaining a queue of inbound RPC requests and responses,
 - [`RequestManager`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/RequestManager.java#L28) for keeping track of in-flight requests, as well as request timeouts, retries and back-off delays,
 - [`QuorumState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/QuorumState.java#L77) for managing the current protocol state and ensuring valid state transitions.

`QuorumState` [uses](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/QuorumState.java#L88) the [`EpochState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/EpochState.java#L22) interface to represent the current protocol state of the node. KRaft node can be in one of the following states represented by the corresponding classes and determining the protocol logic:
 - [`UnattachedState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/UnattachedState.java#L33): the node has learned of an ongoing leader election but has yet to cast its vote or become a candidate itself,
 - [`CandidateState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/CandidateState.java#L30): the node is a candidate in an ongoing leader election,
 - [`VotedState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/VotedState.java#L34): the node has cast its vote for a specific candidate in an ongoing leader election,
 - [`LeaderState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/LeaderState.java#L45): the node considers itself the leader of the current epoch,
 - [`FollowerState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/FollowerState.java#L30): the node is a follower in the current epoch,
 - [`ResignedState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/ResignedState.java#L42): the node has resigned from leadership because it is shutting down or encountered a soft failure.

`LeaderState` [keeps track](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/LeaderState.java#L54-L55) of the follower nodes represented by the [`ReplicaState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/LeaderState.java#L384) class. In particular, this is used to determine the largest offset which is replicated to a majority of replicas and update the high watermark, thus committing the respective replicated log entries. `LeaderState` also holds an instance of the [`BatchAccumulator`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/internals/BatchAccumulator.java#L48) class, which is used to form batches of submitted records to append to the log.

New records are submitted for consensus on the leader node using the [`scheduleAppend`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2317) or [`scheduleAtomicAppend`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2322) method, which both translate into calling private method [`append`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2326). The `append` method [appends](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2333) the records to `BatchAccumulator` and, if needed, [wakes up](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2341) the polling thread [waiting](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2304) on the message queue by calling the [`wakeup`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2273) method. Inbound RPC requests are passed to the [`handle`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2283) method, which simply [appends](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2284) them to the message queue. New log listener registrations are handled by the [`register`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L396) method, which simply [adds](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L397) them to the pending registrations queue and [wakes up](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L398) the polling thread. 

The main entry point of `KafkaRaftClient` is the [`poll`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2291) method. First, `poll` [obtains](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2292) the current timestamp from the abstract local clock. Then it [uses](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2292) the timestamp to check for and handle time-based and pending internal events. In particular, it calls the [`pollCurrentState`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2166) method, which, depending on the current protocol state, [dispatches](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2167-L2179) to the corresponding method. The returned time intervals are used to [calculate](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2299) the timeout until the next expected time-based event. This timeout is used to limit the amount of time spent [waiting](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2304) for a new inbound RPC request or response from the message queue. Inbound requests and responses received from the message queue are [passed](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2310) to the [`handleInboundMessage`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1725) method for handling. Finally, any pending listener registrations are handled by [calling](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2313) the [`pollListeners`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L2184) method.

Inbound RPC requests and responses from the message queue are handled by the [`handleInboundMessage`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1725) method, which, depending on the message type, passes them to the [`handleRequest`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1678) or [`handleResponse`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1602) method. Inbound requests are [dispatched](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1682-L1709) by `handleRequest` to the corresponding method, which returns a future that is [used](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1711) to [complete](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1720) the inbound request with the resulting response once that becomes available. Inbound responses are simply [dispatched](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1607-L1630) by `handleResponse` to the corresponding method and the request state gets [updated](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1632-L1637) in `RequestManager`.

Outbound RPC requests are initiated with the [`maybeSendRequest`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1747) method. It [consults](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1752-L1760) `RequestManager` to check if the remote peer is available for a new request, [assigns](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1761) the requests a new correlation ID, [attaches](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1771-L1785) an action to perform on request completion, and [sends](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1787) the request with `NetworkChannel`, [informing](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1789) `RequestManager` accordingly. The completion action [appends](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1784) the response to the message queue.

`KafkaRaftClient` uses the [`ThresholdPurgatory`](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/internals/ThresholdPurgatory.java#L27) class for two purposes: first, to [defer](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1919) certain actions until a batch of appended requests is considered [committed](https://github.com/apache/kafka/blob/3.6.0/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L299); second, to [wait](https://github.com/apache/kafka/blob/trunk/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L986) until an inbound Fetch requests [can](https://github.com/apache/kafka/blob/trunk/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L285) be [completed](https://github.com/apache/kafka/blob/trunk/raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java#L1018).

Many methods of `KafkaRaftClient` receive the current timestamp as a parameter, which they use to determine if it's time to trigger a time-based event. This ensures determinism in terms of the abstract local clock. Such methods often return a time interval until the next expected event to be triggered by that method. Those time intervals are used to determine the maximal time to wait for external events when polling. Another common pattern is returning a boolean or `Option` to indicate if the event is fully handled by the invoked method or it requires further handling.

### Tracing and Controlling Execution

For simple diagnostic logging, Kafka uses [slf4j](http://www.slf4j.org/index.html); in addition to that, the [`LogContext`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/utils/LogContext.java#L33) class allows creating loggers with a context automatically enriching log messages. The code also collects various telemetry metrics using the [`Metrics`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/metrics/Metrics.java#L69) class as the metrics registry.

`KafkaRaftClient` is deterministic in terms of time, thanks to the local time abstraction [`Time`](https://github.com/apache/kafka/blob/3.6.0/clients/src/main/java/org/apache/kafka/common/utils/Time.java#L31), and can be supplied with an instance of the [`Random`](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html) class to ensure full determinism. This is used in [discrete-event simulation testing framework](https://github.com/apache/kafka/blob/3.6.0/raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java) which provides reproducible testing of a cluster on nodes. Simulation behavior is deterministic provided an initial random seed. This makes it easy to reproduce and debug test failures. All communication happens within the same process and persistent state is stored in memory. The framework uses a single event scheduler in order to provide deterministic executions.
